language: csharp
sudo: required
dist: trusty
env:
  global:
    secure: m2PtYwYOhaK0uFMZ19ZxApZwWZeAIq1dS//jx/5I3txpIWD+TfycQMAWYxycFJ/GJkeVF29P4Zz1uyS2XKKjPJpp2Pds98FNQyDv3OftpLAVa0drsjfhurVlBmSdrV7GH6ncKfvhd+h7KVK5vbZc+NeR4dH7eNvN/jraS//AMJg=
mono: beta
dotnet: 1.0.4
os:
  - linux
  - osx
osx_image: xcode7.3

script:
  - ./build.sh --target All --publish-all --archive

addons:
  apt:
    packages:
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - libssl-dev
      - libunwind8
      - zlib1g
      - curl

notifications:
  slack:
    rooms:
      - omnisharp:U358j4McaEOIzFqXvGexVokC#general
    on_success: change
    on_failure: always
    on_pull_requests: false

before_deploy:
  - |
    # Only deploy OSX-specific OmniSharp from the OSX.
    # All other builds should be deployed by Linux CI.
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      rm artifacts/package/omnisharp-osx.tar.gz
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      rm artifacts/package/mono.tar.gz
      rm artifacts/package/omnisharp-linux-x86.tar.gz
      rm artifacts/package/omnisharp-linux-x64.tar.gz
    fi

deploy:
  provider: releases
  api_key:
    secure: EsRemh0XwJc3jhIjaxSuAhcm0AGjFwa3HO6oWzJOoupX0l+HV5CxrJqui//sqJ/jK4nnwNcTfMyMFTAz2t6nWCmuwuezTncty/uNTXE0Whe+3WWc/BakfEdBrCfnRhGhwQ5EW2Y6BasuF0f/hpjnucqpNxcKmKOZvThzv93bmSA=
  file_glob: true
  file: artifacts/package/*.tar.gz
  skip_cleanup: true
  on:
    repo: OmniSharp/omnisharp-roslyn
    tags: true

after_deploy: |
  openssl enc -aes-256-cbc -a -salt -in travis_rsa.enc -out ~/.ssh/id_rsa -pass pass:$OPENSSL_PASSKEY -d
  chmod 600 ~/.ssh/id_rsa
  eval `ssh-agent -s`
  ssh-add ~/.ssh/id_rsa
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    OMNISHARP_VERSION="1.0.0-dev";
    if [ $TRAVIS_TAG ]; then
      OMNISHARP_VERSION=${TRAVIS_TAG:1};
    fi
    BRANCH_NAME="upgrade/omnisharp-roslyn-$TRAVIS_TAG"
    git config --global user.name "OmniSharp Bot"
    git config --global user.email "omnisharp-bot@users.noreply.github.com"
    git clone git@github.com:OmniSharp/omnisharp-node-client.git ~/omnisharp-node-client
    pushd ~/omnisharp-node-client
    git checkout -b $BRANCH_NAME
    cat package.json > package2.json
    cat package2.json | jq '."omnisharp-roslyn"="'$TRAVIS_TAG'"' > package.json
    git add package.json
    git commit -m "Update omnisharp-roslyn to $TRAVIS_TAG"
    git push origin $BRANCH_NAME
    curl -X POST -H 'Authorization: token '$GITHUB_API_TOKEN'' -d '{ "title": "Upgrade to OmniSharp/omnisharp-roslyn '$TRAVIS_TAG'", "body": "*Automated PR*  -  Upgrade omnisharp-roslyn to '$TRAVIS_TAG'. [release patch]", "head": "'$BRANCH_NAME'", "base": "master" }' https://api.github.com/repos/OmniSharp/omnisharp-node-client/pulls
  fi
